"""initial schema

Revision ID: e64da3d498d8
Revises:
Create Date: 2026-07-29 16:04:36.356688+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "e64da3d498d8"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ad_accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("business_name", sa.String(length=255), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("timezone_name", sa.String(length=64), nullable=True),
        sa.Column("account_status", sa.Integer(), nullable=True),
        sa.Column("spend_cap", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("amount_spent", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("remote_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ad_accounts")),
    )
    op.create_index(op.f("ix_ad_accounts_remote_id"), "ad_accounts", ["remote_id"], unique=True)
    op.create_table(
        "ad_creatives",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ad_account_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("call_to_action_type", sa.String(length=64), nullable=True),
        sa.Column("object_type", sa.String(length=64), nullable=True),
        sa.Column("thumbnail_url", sa.String(length=2048), nullable=True),
        sa.Column("image_url", sa.String(length=2048), nullable=True),
        sa.Column("video_id", sa.String(length=64), nullable=True),
        sa.Column("remote_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ad_account_id"],
            ["ad_accounts.id"],
            name=op.f("fk_ad_creatives_ad_account_id_ad_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ad_creatives")),
    )
    op.create_index(
        op.f("ix_ad_creatives_ad_account_id"), "ad_creatives", ["ad_account_id"], unique=False
    )
    op.create_index(op.f("ix_ad_creatives_remote_id"), "ad_creatives", ["remote_id"], unique=True)
    op.create_table(
        "campaigns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ad_account_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "paused",
                "deleted",
                "archived",
                "unknown",
                name="campaign_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("effective_status", sa.String(length=64), nullable=True),
        sa.Column("objective", sa.String(length=64), nullable=True),
        sa.Column("buying_type", sa.String(length=64), nullable=True),
        sa.Column("bid_strategy", sa.String(length=64), nullable=True),
        sa.Column("daily_budget", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("lifetime_budget", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stop_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("remote_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ad_account_id"],
            ["ad_accounts.id"],
            name=op.f("fk_campaigns_ad_account_id_ad_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaigns")),
    )
    op.create_index(
        op.f("ix_campaigns_ad_account_id"), "campaigns", ["ad_account_id"], unique=False
    )
    op.create_index(op.f("ix_campaigns_remote_id"), "campaigns", ["remote_id"], unique=True)
    op.create_table(
        "insight_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ad_account_id", sa.Integer(), nullable=False),
        sa.Column(
            "level",
            sa.Enum(
                "account",
                "campaign",
                "adset",
                "ad",
                name="insight_level",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("entity_remote_id", sa.String(), nullable=False),
        sa.Column("entity_name", sa.String(), nullable=True),
        sa.Column("date_start", sa.Date(), nullable=False),
        sa.Column("date_stop", sa.Date(), nullable=False),
        sa.Column("spend", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("impressions", sa.BigInteger(), nullable=False),
        sa.Column("clicks", sa.BigInteger(), nullable=False),
        sa.Column("reach", sa.BigInteger(), nullable=False),
        sa.Column("conversions", sa.BigInteger(), nullable=False),
        sa.Column("conversion_value", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ad_account_id"],
            ["ad_accounts.id"],
            name=op.f("fk_insight_records_ad_account_id_ad_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_insight_records")),
        sa.UniqueConstraint(
            "level", "entity_remote_id", "date_start", "date_stop", name="entity_reporting_window"
        ),
    )
    op.create_index(
        "ix_insight_records_account_level_date",
        "insight_records",
        ["ad_account_id", "level", "date_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_insight_records_ad_account_id"), "insight_records", ["ad_account_id"], unique=False
    )
    op.create_index(
        op.f("ix_insight_records_entity_remote_id"),
        "insight_records",
        ["entity_remote_id"],
        unique=False,
    )
    op.create_table(
        "recommendations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ad_account_id", sa.Integer(), nullable=False),
        sa.Column(
            "level",
            sa.Enum(
                "account",
                "campaign",
                "adset",
                "ad",
                name="recommendation_level",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("entity_remote_id", sa.String(), nullable=False),
        sa.Column("entity_name", sa.String(length=255), nullable=True),
        sa.Column("rule_code", sa.String(length=64), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "info",
                "warning",
                "critical",
                name="recommendation_severity",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "action",
            sa.Enum(
                "increase_budget",
                "decrease_budget",
                "pause_entity",
                "rotate_creative",
                "review_targeting",
                "review_conversion_tracking",
                name="recommendation_action",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "applied",
                "dismissed",
                "superseded",
                name="recommendation_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("metric_snapshot", sa.JSON(), nullable=False),
        sa.Column("suggested_change", sa.JSON(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ad_account_id"],
            ["ad_accounts.id"],
            name=op.f("fk_recommendations_ad_account_id_ad_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommendations")),
    )
    op.create_index(
        "ix_recommendations_account_status",
        "recommendations",
        ["ad_account_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommendations_ad_account_id"), "recommendations", ["ad_account_id"], unique=False
    )
    op.create_index(
        "ix_recommendations_entity_rule",
        "recommendations",
        ["entity_remote_id", "rule_code"],
        unique=False,
    )
    op.create_table(
        "ad_sets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "paused",
                "deleted",
                "archived",
                "unknown",
                name="ad_set_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("effective_status", sa.String(length=64), nullable=True),
        sa.Column("optimization_goal", sa.String(length=64), nullable=True),
        sa.Column("billing_event", sa.String(length=64), nullable=True),
        sa.Column("daily_budget", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("lifetime_budget", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("bid_amount", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("remote_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_ad_sets_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ad_sets")),
    )
    op.create_index(op.f("ix_ad_sets_campaign_id"), "ad_sets", ["campaign_id"], unique=False)
    op.create_index(op.f("ix_ad_sets_remote_id"), "ad_sets", ["remote_id"], unique=True)
    op.create_table(
        "ads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ad_set_id", sa.Integer(), nullable=False),
        sa.Column("creative_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "paused",
                "deleted",
                "archived",
                "unknown",
                name="ad_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("effective_status", sa.String(length=64), nullable=True),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("remote_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ad_set_id"], ["ad_sets.id"], name=op.f("fk_ads_ad_set_id_ad_sets"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["creative_id"],
            ["ad_creatives.id"],
            name=op.f("fk_ads_creative_id_ad_creatives"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ads")),
    )
    op.create_index(op.f("ix_ads_ad_set_id"), "ads", ["ad_set_id"], unique=False)
    op.create_index(op.f("ix_ads_creative_id"), "ads", ["creative_id"], unique=False)
    op.create_index(op.f("ix_ads_remote_id"), "ads", ["remote_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ads_remote_id"), table_name="ads")
    op.drop_index(op.f("ix_ads_creative_id"), table_name="ads")
    op.drop_index(op.f("ix_ads_ad_set_id"), table_name="ads")
    op.drop_table("ads")
    op.drop_index(op.f("ix_ad_sets_remote_id"), table_name="ad_sets")
    op.drop_index(op.f("ix_ad_sets_campaign_id"), table_name="ad_sets")
    op.drop_table("ad_sets")
    op.drop_index("ix_recommendations_entity_rule", table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_ad_account_id"), table_name="recommendations")
    op.drop_index("ix_recommendations_account_status", table_name="recommendations")
    op.drop_table("recommendations")
    op.drop_index(op.f("ix_insight_records_entity_remote_id"), table_name="insight_records")
    op.drop_index(op.f("ix_insight_records_ad_account_id"), table_name="insight_records")
    op.drop_index("ix_insight_records_account_level_date", table_name="insight_records")
    op.drop_table("insight_records")
    op.drop_index(op.f("ix_campaigns_remote_id"), table_name="campaigns")
    op.drop_index(op.f("ix_campaigns_ad_account_id"), table_name="campaigns")
    op.drop_table("campaigns")
    op.drop_index(op.f("ix_ad_creatives_remote_id"), table_name="ad_creatives")
    op.drop_index(op.f("ix_ad_creatives_ad_account_id"), table_name="ad_creatives")
    op.drop_table("ad_creatives")
    op.drop_index(op.f("ix_ad_accounts_remote_id"), table_name="ad_accounts")
    op.drop_table("ad_accounts")
    # ### end Alembic commands ###
